### ISSUE TITLE
Comments swagger edit not working

### ISSUE THREAD

**Issue by MohitMotiani99** [MohitMotiani99/skill_enhancement_final#1] opened 2021-09-10 15:17 UTC
@Archith48 please check the swagger of comments edit api , not working for me

**Comment by MohitMotiani99** [comment] 2021-09-12 14:51
same with vote,wherever redirect is required

**Comment by Archith48** [comment] 2021-09-13 05:34
The issue is resolved by replacing the redirect with send

**Closed as completed by Archith48** 2021-09-13 05:34 UTC
